apiVersion: v1
kind: Service
metadata:
  name: commonplace
  namespace: cwb
  labels:
    app: commonplace
spec:
  type: ClusterIP
  selector:
    app: commonplace
  ports:
    - name: http
      port: 8101
      targetPort: http
      protocol: TCP
